
page(
  name='readme',
  source='README.md',
  dependencies=[
    'src/python/pkg:readme',
  ],
  provides=[
    wiki_artifact(
      wiki=confluence,
      space='DOCS',
      title='Python Libraries',
      parent='Software Docs - Home',
    ),
  ],
)
